### ISSUE TITLE
Create R library path on MyData. 

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#10]
All R libraries on Linux are need to be build from the scratch. Because each of those also have a number of dependencies, quickly building up a R package scale up to 10-15 minutes. And some large packages (ANTsRCore, ITKR) may even take up to an hour or so. 

I already created a MorphoCloudCEPH share in which these built libraries are copied. We just need to copy them from that location to **/home/exouser/R** each time an instance created.

**Comment by muratmaga** [comment]
Instead of copying the files we should do this: 
1. Mount this share as R/O (/media/share/MorphoCloudCephShare/)
2. If it doesn't exist alread, create this folder in user's MyData volume:
```
R/x86_64-pc-linux-gnu-library/4.2/
```
4. Create an **.Renvion** file in /home/exouser with contents:
```
R_LIBS_SITE=/media/share/MorphoCloudCephShare/R/x86_64-pc-linux-gnu-library/4.2/
R_LIBS_USER=/media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.2/
```
This way, users will benefit from the precompiled R libraries in the CEPH share, and any library they will will be saved into their persistent MyData volume. This variables are hard coded to R 4.2. For that to work, they should launch their R/Rstudio session with command module load rstudio/2022---XXXXX 

(The default is 4.4, which becomes available through module load rstudio. I am sure there is a way to encode the paths as so that if they are launching 4.4, files are written to 4.4 path. But for the time being let's operate under the assumption that they will be using the older R.

**Comment by jcfr** [comment]
To support mounting the share, the following variables should first be set in the context of the GitHub runner:

```
SHARE_NAME=MorphoCloudCephShare

SHARE_PATH=$(openstack share show $SHARE_NAME -f json \
  | jq -r '.export_locations | split("\n") | .[] | select(startswith("path = ")) | sub("^path = "; "")')
SHARE_ACCESS_KEY=$(openstack share access list $SHARE_NAME -f json \
  | jq --arg share_name "$SHARE_NAME" -r '.[] | select(.["Access To"] == ($share_name + "-ro")) | .["Access Key"]')
```

Then, the following command should be executed on the instance through ssh:

```
mount_ceph_script=/opt/instance-config-mgt/assets/scripts/mount_ceph.py

sudo python3 $mount_ceph_script mount \
  --access-rule-name="$SHARE_NAME-ro" \
  --access-rule-key="$SHARE_ACCESS_KEY" \
  --share-path="$SHARE_PATH" \
  --share-name="$SHARE_NAME"
```

**Comment by muratmaga** [comment]
@jcfr this is no longer a high priority. I made a tutorial for this for the workshop attendees, this we can comeback for a consistent design (for example bundle the script inside the instance). 

Can you focus on the Renviron part?

**Comment by jcfr** [comment]
For future reference, the command to execute from the runner to mount/unmount are the following:

```
SHARE_NAME=MorphoCloudCephShare

SHARE_PATH=$(openstack share show $SHARE_NAME -f json | jq -r '.export_locations | split("\n") | .[]| select(startswith("path = ")) | sub("^path = "; "")')

SHARE_ACCESS_KEY=$(openstack share access list $SHARE_NAME -f json | jq --arg share_name "$SHARE_NAME" -r '.[] | select(.["Access To"] == ($share_name + "-ro")) | .["Access Key"]'
)
```

**Mount:**

```
INSTANCE_IP=X.X.X.X

ssh \
  -o StrictHostKeyChecking=no \
  -o UserKnownHostsFile=/dev/null \
  -o LogLevel=ERROR \
  exouser@$INSTANCE_IP \
  "mount_ceph_script=/opt/instance-config-mgt/assets/scripts/mount_ceph.py && \
   sudo python3 \$mount_ceph_script mount \
     --access-rule-name=\"${SHARE_NAME}-ro\" \
     --access-rule-key=\"${SHARE_ACCESS_KEY}\" \
     --share-path=\"${SHARE_PATH}\" \
     --share-name=\"${SHARE_NAME}\""
```

**Unmount:**

```
INSTANCE_IP=X.X.X.X

ssh \
  -o StrictHostKeyChecking=no \
  -o UserKnownHostsFile=/dev/null \
  -o LogLevel=ERROR \
  exouser@$INSTANCE_IP \
  "mount_ceph_script=/opt/instance-config-mgt/assets/scripts/mount_ceph.py && \
   sudo python3 \$mount_ceph_script unmount \
     --share-name=\"${SHARE_NAME}\""
```

**Comment by jcfr** [comment]
I confirm that the file `.Renviron` is created:

```
exouser@morpho-cloud-portal-instance-100:~$ cat .Renviron
R_LIBS_SITE=/media/share/MorphoCloudCephShare/R/x86_64-pc-linux-gnu-library/4.4/
R_LIBS_USER=/media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.4/
```

**Comment by jcfr** [comment]
This has been implemented and deployed across multiple projects:

1. **`MorphoCloudWorkflow`** vis commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/77076cfe4c093f0b26cef424c699559374344318
2. **`MorphoCloudInstances`** via https://github.com/MorphoCloud/MorphoCloudInstances/commit/13a9d60c27870896275e8f0b9831aa1a38c3e482

**Comment by muratmaga** [comment]
@jcfr reopening this issue:
While the .Renviron is correct, if the `/media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.4/` doesn't exist, than it removes that path from the libPaths and then R defaults to /home/exouser/R/4.4, which we don't want. You will have to create this folder during the instance creation (if it doesn't exist).

`/media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.4/`

**Comment by jcfr** [comment]
> Re: create folder
Sounds good. I will add a call to `mkdir`

> Re: missing package
I will add those to the ansible Slicer role.

**Comment by jcfr** [comment]
Follow-up fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/5c85c9170fbb8ddee99d4c81811ce3468b0279a8
2. **`MorphoCloudWorkflow`** via commits https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/76aad0ed493978952fcf4a99a4cbddac424ade42..7e99a4501a41da386c015050151b420f7e76a600
3. **`MorphoCloudInstances`** via https://github.com/MorphoCloud/MorphoCloudInstances/commit/43e192ec903ff9f428b8ac085154e77cf36ddef4


----


* Folder created ✅ 

  ```
  exouser@morpho-cloud-portal-instance-101:/media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.4$ pwd
  /media/volume/MyData/R/x86_64-pc-linux-gnu-library/4.4
  ```

* ✅  Packages `tcllib` and `tklib` installed 

  ```
  exouser@morpho-cloud-portal-instance-101:~$ sudo apt-get install tcllib tklib
  Reading package lists... Done
  Building dependency tree... Done
  Reading state information... Done
  tcllib is already the newest version (1.20+dfsg-1).
  tklib is already the newest version (0.7+20210111-1).
  0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
  ```
