### ISSUE TITLE
Automatic shelving

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#11]
After 4h of up time, the instance should shelve itself automatically. 10-15 minutes before this, the user needs to be warned about impeding shevling so that they have a chance to save their work and gracefully shelve the instance themselves.

**Comment by jcfr** [comment]
Implemented in:
* https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/06a8f260a097b4cd46fe53bfae1c2e082fa43e1b
* https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/e37edfa51691c1e80cfb2468007a9bb7366189fc
