### ISSUE TITLE
Trigger an email first time an instance request is made

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#12]
At this point I do not have a mechanism to get notified when someone asks to get an instance. The email associated with the github account does receive them, but that's very verbose, since every issue and comment triggers an email. This email needs to go my work account, with a specific title so that I can create filter based on it.

**Comment by jcfr** [comment]
![image](https://github.com/user-attachments/assets/29d780bd-dd5f-468a-84ba-80825095e5f8)

![image](https://github.com/user-attachments/assets/6fd7e706-d6d9-4728-bdf2-1807aa2d81c3)

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/ba4cb59d4cad22b2187c64275cad2db926d1a9f5
