### ISSUE TITLE
Make the email send to the users more informative

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#14]
Currently the email sent is too terse, and almost look like a phishing email. We need to communicate better. Below is my attempts:

```
Your MorphoCloud instance is up and running. To access the access through the graphical user interface use the provided weblink. To access the instance from command line, use the SSH information provided. In both cases, username is **exouser** and the current passphrase is provided.

Note that each session is limited to 4h, after which your instance is automatically shelved. To unshelve an existing instance, use the **/unshelve** command. To shelve an instance, and preserve your allocation, use the **/shelve** command. To obtain the latest set of access credentials, use the **/email** command. 

You can find more information about the instances and how to use them at: htttps:/......

If you have questions, please contact morphocloud-support@gmail.com. 
```

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/0866ea45b7983a3e9cce352e5b44ed80bd03f84c

![image](https://github.com/user-attachments/assets/b77e4029-3a67-4f0b-99bc-79c0838514f2)

**Comment by muratmaga** [comment]
Thanks JC. One more favor, please update the email address to morphocloud@outlook.com. That will be the official point of contact for the support. (apparently gmail is taken).

**Comment by jcfr** [comment]
> please update the email address

Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/33c46fccc30bd37d3d4c2accae30bbf338688e2e
