### ISSUE TITLE
MyData folder is not visible within Slicer dialog boxes.

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#17]
This is probably a QT issue, but it is a major challenge, since people cannot navigate to the MyData directly within Slicer. 

if it is not easily fixable, consider adding the shortcut to /media/MyData as a favoriates folder to Slicer I/O dialog boxes.

**Comment by jcfr** [comment]
Possibly related issues:
* https://github.com/Slicer/Slicer/issues/7674

**Comment by muratmaga** [comment]
Actually taking a closer look, that My Data icon on the desktop is not a folder, some sort of a shortcut to **/media/volume/My-Data**
There is no soft link or anything, even when I do ls -l inside Desktop, so it is normal that it is not visible in Slicer (since it is not visible in the Linux file browser too). 
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/96d6ff6b-9663-41d6-b855-1c9e4c0777f2">

**Comment by muratmaga** [comment]
Now that Slicer scene location and upload/download location is defaulted to MyData, this less concerning.
