### ISSUE TITLE
programmatically change default scene location to MyData

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#18]
To give a consistent experience with file uploads (and avoid issues with data loss), we should probably force Slicer to use MyData as a the default scene location.

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/exosphere/compare/ed8864743...80d1836fc integrated into `MorphoCloudWorkflow` through https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/8ea5fa089d7cffb4ae28762bf39fe1df9714d8cd

**Comment by jcfr** [comment]
![image](https://github.com/user-attachments/assets/d1bd0c6c-8127-4582-b5fd-fddb88347db7)
