### ISSUE TITLE
Add the issues page link to the email command. 

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#24]
Since the email sent with access credentials serves as a short guide for commands and how to interact with the MorphoCloud, it would be important to add the direct URL for the issues page for the convenience of the user. 

If the email is generated in response to Issue #35, the link to include in the email should be:

https://github.com/MorphoCloud/MorphoCloudInstances/issues/35

as bullet under the Important Notes.

**Comment by jcfr** [comment]
Text like the following was added:

* Commands should be added as comments to issue [jcfr/MorphoCloudPortal#87](https://github.com/jcfr/MorphoCloudPortal/issues/87)


| Preview | 
| -- |
| ![image](https://github.com/user-attachments/assets/44aed860-f75e-42ba-9b3e-2b3ca802ea25) |

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/0ea26c777dc9a280f2c9117629ad8ba795b4e83c
