### ISSUE TITLE
Feedback from MorphoCloud PI Meeting

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#27]
Some usability requirements from the PI Meeting:

1. Add the command list with their synopsis to the body of the email sent to the user. 

2. Automatically send the access credentials email every time the instance is unshelved (since the IP address and/or passphrase might have changed), as opposed to have the user try the old ones, and if it fails request  the credentials explicityly by /email command.

~3. Once unshelved, the label (active) did not get updated for  instance #30 at the same time when the command history showed that it the command is successfully executed (and indeed the instance was available). It was about 5 minutes or so...~

4. When requesting an instance, have the user enter their email name twice, and if it checkouts, obfuscate the email right away. We have already someone snooping and sending fake emails to people (see the screenshot), which is very serious issue since our users can't tell whether this is legit or not.
<img width="628" alt="image" src="https://github.com/user-attachments/assets/0c4c9069-9671-46a4-bf5c-d9b5d83b7828">

**Comment by jcfr** [comment]
Closing. Issues tracking each request have been created.
