### ISSUE TITLE
Revisit obfuscation of email associated with instance request

### ISSUE THREAD

**Issue by jcfr** [MorphoCloud/MorphoCloudWorkflow#31]
When requesting an instance, have the user enter their email name twice, and if it checkouts, obfuscate the email right away. We have already someone snooping and sending fake emails to people (see the screenshot), which is very serious issue since our users can't tell whether this is legit or not.

<img width="50%" alt="image" src="https://github.com/user-attachments/assets/0c4c9069-9671-46a4-bf5c-d9b5d83b7828">

_Originally posted by @muratmaga  in https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/27#issue-2487721000_

**Comment by jcfr** [comment]
After further analysis, the issue is related to a "bot" account that commented on the issue and is independent of the email of the  researcher who created the account.

The corresponding account has been reported.

**Comment by jcfr** [comment]
For context, here is another example of such comment. See https://github.com/jcfr/MorphoCloudPortal/issues/88#issuecomment-2312935572

**Comment by jcfr** [comment]
After reporting the account to GitHub, it has now been "removed"

**Comment by muratmaga** [comment]
Thanks @jcfr. I think we still want to implement the double entry of the email (to double check) and automatic obfuscate for privacy issues.

**Comment by jcfr** [comment]
To handle the case when the two entries do not match, I suggest to:
* flag when those do not match
* skip the automatic obfuscation
* expect the user to edit the request and enter `/encode_email` explicitly 

If the two email do match, email will automatically be encoded (aka obfuscated)

Does this sound reasonable?

**Comment by muratmaga** [comment]
It would be better, if the user cannot proceed or submit the ticket if the emails are not identical (or somehow give real-time feedback), but I understand that may not be possible with GH issues.

**Comment by jcfr** [comment]
This feature has been implemented in `MorphoCloudWorkflow` via commits https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/c95e0a90112433d6ab0fed56285a25ff8851d5f0...8da1de97fa238482f4dd4dfe04666435988c3197 and deployed in `MorphoCloudInstances` via https://github.com/MorphoCloud/MorphoCloudInstances/commit/a1db54707b3fcc07e44426d44948e8fcb42b32e7

It introduce a new field called "Confirm Email". If emails are valid and match, they will be automatically obfuscated.

If not, relevant hints are displayed.

Once the issue description has been updated with valid and matching emails, obfuscation is automatically triggered.

This can be observed reviewing comments in https://github.com/jcfr/MorphoCloudPortal/issues/95#issuecomment-2433530516
