### ISSUE TITLE
Install the firefox via apt mechanism, remove the snap package

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#34]
From Julian Pistorius:

https://balintreczey.hu/blog/firefox-on-ubuntu-22-04-from-deb-not-from-snap/

**Comment by jcfr** [comment]
Based on @julianpistorius comment in email titled `Re: ATS-9869 [Jetstream2] Firefox stops working after a couple of shelvings/unshelvings` from August 14th:

> It shouldn’t be using the Firefox snap at all. This instance might be based on an older image. 

@julianpistorius Could you confirm that this "issue" is specific to older instance relying on older base image ?

**Comment by julianpistorius** [comment]
Hello @jcfr. Yes, I believe so. If this still happens in new instances created from recent images then this is a bug, and we'll fix it.

**Comment by jcfr** [comment]
After creating a new instance, I can confirm firefox is not installed through snap:

```
$ snap list
Name               Version          Rev    Tracking       Publisher   Notes
bare               1.0              5      latest/stable  canonical?  base
core20             20240705         2379   latest/stable  canonical?  base
core22             20240904         1621   latest/stable  canonical?  base
gnome-42-2204      0+git.510a601    176    latest/stable  canonical?  -
gtk-common-themes  0.1-81-g442e511  1535   latest/stable  canonical?  -
lxd                5.0.3-80aeff7    29351  5.0/stable/?   canonical?  -
snapd              2.63             21759  latest/stable  canonical?  snapd
```
