### ISSUE TITLE
obfuscate emails & validate ORCID

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#4]
* [ ] Email address needs to be hidden (high priority)
* [ ] ORCID field needs to be limited to 16 characters (without dashes).

**Comment by jcfr** [comment]
> Email address needs to be hidden 

To give a chance to the user to review the email, at first the email can now be obfuscated/deobfuscated using the new commands `encode_email` and `decode_email`

**Comment by jcfr** [comment]
> ORCID field needs to be limited to 16 characters 

Validation has been added. And to comply with the `Expressing the ORCID iD` section of the specification, the requirement for dashes has been maintained.

See https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/compare/7fee216...5ef9460
