### ISSUE TITLE
Screen resolution limitation in xfce4 

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#46]
In the new ubuntu 22.04 image JS2 provides, display properties can be adjusted up to resolution user's monitor support (see first screenshot). 

![image](https://github.com/user-attachments/assets/0d951a00-ff49-400e-b2a4-6e6b7eecb53b)

However, in our XFCE4 customizations it is capped at 1920x1200, which looks extremely oversized in high-resolution screens. 

![image](https://github.com/user-attachments/assets/daa60f98-42cf-4c05-b268-0b2aefdc9831)

I was under the impression this is OS controlled, so not sure why our customization is not showing those.

**Comment by jcfr** [comment]
After running the following script:

```bash
OUTPUT="VNC-0"

# List of resolutions to add
RESOLUTIONS=(
  "3200 1800 60.00"
  "2880 1800 60.00"
  "2560 1600 60.00"
  "2560 1440 60.00"
  "2048 1536 60.00" 
  "2048 1152 60.00"
)

for RES in "${RESOLUTIONS[@]}"; do
  WIDTH=$(echo $RES | cut -d' ' -f1)
  HEIGHT=$(echo $RES | cut -d' ' -f2)
  RATE=$(echo $RES | cut -d' ' -f3)
  
  MODELINE=$(cvt $WIDTH $HEIGHT $RATE | grep "Modeline" | sed 's/Modeline //' | tr -d '"')
  MODENAME=$(echo $MODELINE | cut -d' ' -f1 | tr -d '"')
  
  xrandr --newmode $MODELINE
  xrandr --addmode $OUTPUT $MODENAME
done
```

we are able to select the missing resolution:

![image](https://github.com/user-attachments/assets/541175fd-8944-4df8-8363-21b634e51244)

**Comment by jcfr** [comment]
Next step: Add missing mode on instance creation

**Comment by jcfr** [comment]
Attempted to have a script called `xrandr-add-modes.sh` automatically automatically executed upon login by adding the following `.desktop` file, but the corresponding display modes are not added after restarting the instance through `Log Out -> Restart`:

```
$ cat .config/autostart/xfce4-xrandr-add-modes.desktop
[Desktop Entry]
Type=Application
Name=Xfce Xrandr Add Modes
Exec=/opt/instance-config-support/dist/xrandr-add-modes.sh
OnlyShowIn=XFCE;
NoDisplay=true
```

**Comment by jcfr** [comment]
After addition experiments, modifying the system wide file `/etc/vnc/xstartup` is to call `xrandr-add-modes.sh` before starting Xfce ensure the modes are available for selection.

**Comment by jcfr** [comment]
Follow-up fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/3097269c0961caf198ff54b021f363f121bc2d6a
2. **`MorphoCloudWorkflow`** via commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/1bd46e9538b8298df0d0637b3921f6b9c4c6a9a1
3. **`MorphoCloudInstances`** via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/528d9b9be8ede773bdf832d5076342aaa5eba0ff


-----

We can confirm that updating `/etc/vnc/xstartup` script to call `xrandr-add-modes.sh` works ✅ 

![image](https://github.com/user-attachments/assets/9563a6ee-4533-4eea-b5fc-94b6c29bbda8)
