### ISSUE TITLE
add gh cli to the install packages for the instance image

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#47]
Needed for morphoDepot. Ubuntu provided version is too old for our purposes. 

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

**Comment by jcfr** [comment]
This has been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/d6a32c58c922614c9f3d9c2232f2464f0b81fc02 by updating the Slicer ansible role adding tasks for installing the Github Client
2. **`MorphoCloudWorkflow`** vis commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/14f8e42dd646c0b5e2c5fb438e78cd6dfca7e325
3. **`MorphoCloudInstances`** via https://github.com/MorphoCloud/MorphoCloudInstances/commit/e9354ea9435c9476314a729fd584bad81d2da033
