### ISSUE TITLE
Increase `create-instance` workflow polling timeout to 20minutes

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#53]

**Comment by jcfr** [comment]
This has been implemented and deployed across multiple projects:

1. **`MorphoCloudWorkflow`** vis commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/76aad0ed493978952fcf4a99a4cbddac424ade42
2. **`MorphoCloudInstances`** via https://github.com/MorphoCloud/MorphoCloudInstances/commit/8882e0c0125ae10cceab55f93d5a5fe26eb73510
