### ISSUE TITLE
Install preview version of Slicer

### ISSUE THREAD

**Issue by jcfr** [MorphoCloud/MorphoCloudWorkflow#57]
We will have to use preview version of Slicer on the cloud. I will add this comment for tracking purposes.

_Originally posted by @muratmaga in https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/54#issuecomment-2498499379_

**Comment by amm554** [comment]
Sara is going to incorporate some changes today. We will test it with tomorrow (Nov 26th) build, and if all checks out you can specific that or November 27 build (Wednesday one) as the Slicer version on the cloud.

**Comment by muratmaga** [comment]
There is a fix that is going to be incorporated tonight, but everyhting else seems to work. You can go ahead an plan on incorporating tonight's build to MorphoCloud.

**Comment by jcfr** [comment]
![image](https://github.com/user-attachments/assets/1c06070f-6527-4167-bbd2-b4b0186f5bb7)

**Comment by jcfr** [comment]
Follow-up fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/47914b299aad8b7d30283b7e8974ef4fdd100bab
2. **`MorphoCloudWorkflow`** via commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/a7c6c02d9bfcdec10f244c02bdde739c3da45919
3. **`MorphoCloudInstances`** via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/d5d544ae6a56f3c0f32e997081dd2de8db56959d
