### ISSUE TITLE
VLC is dropped from the list of applications to be installed

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#64]
New instances do not have vlc installed. Please add 
`sudo apt install vlc -y`

to the provisioning script.

**Comment by jcfr** [comment]
Currently `vlc-bin`[^1] is being installed, see https://github.com/MorphoCloud/exosphere/commit/28cf6695f4c80d2747f26c7ea91470259974d980 (`[MorphoCloud] Update Ubuntu.yml to install ffmpeg and vlc-bin`)

I will switch the package from `vlc-bin` to `vlc`[^2] to ensure a vlc and plugins are installed.

[^1]: https://packages.ubuntu.com/jammy/vlc-bin
[^2]: https://packages.ubuntu.com/jammy/vlc

**Comment by jcfr** [comment]
Fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/55bf29b31
2. **`MorphoCloudWorkflow`** via commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/605af1204223a7361811d1b026c70f4499bec249
3. **`MorphoCloudInstances`** via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/ee56e8792027964409c1e01dd088e22b979bc2e6


----

![image](https://github.com/user-attachments/assets/f9083191-cb26-4b07-994e-0d1a84eaa1fe)
