### ISSUE TITLE
Switch to 550 series non-grid NVIDIA driver to resolve torch and cuda issues.

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#66]
From JS2 admins on torch and cuda issues:

https://discourse.slicer.org/t/pytorch-warning-error-about-torchvision/40476/7?u=muratmaga

We might want to do this with

**Comment by muratmaga** [comment]
Actually this turned into a very blocking issue. We can't run any of the deep learning models, not consistenyly at least. it is too late for the workshop, but we should update the drivers and test and if it resolves should deploy quickly.

**Comment by muratmaga** [comment]
https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/63

**Comment by jcfr** [comment]
Copied from https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/63

> ![image](https://private-user-images.githubusercontent.com/21285140/391647920-45c4d37f-f8a9-4cce-83a1-a9a6ab0a81ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzMzNzMsIm5iZiI6MTczMzc3MzA3MywicGF0aCI6Ii8yMTI4NTE0MC8zOTE2NDc5MjAtNDVjNGQzN2YtZjhhOS00Y2NlLTgzYTEtYTlhNmFiMGE4MWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE5Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOTIyYTY2ZGM5NmFhMGRlNTMzY2MxNjllMmYwMGZlZDAxNWU4MGQ1ZmQ4ZjIwOTBiMzQxZWQ1M2RkZTVhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.474OHLChWh4tm9JhR9zXxik8DWhE-nSG7BLZY-h9rqU)

**Comment by jcfr** [comment]
Despite of having the driver `nvidia-driver-550-server-open` installed, attempting to run TotalSegmentator is not using the GPU:

![image](https://github.com/user-attachments/assets/f44473b7-3840-42f2-b8fe-6cdacb5b14c9)

**Comment by muratmaga** [comment]
Ok i will try later tonight with memos. Does torch install the cuda version?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jcfr** [comment]
> Ok i will try later tonight with memos

Since the change is currently only associated with the test project, make sure to create a request from https://github.com/MorphoCloud/MorphoCloudInstancesTest

Which is now associated with the `BIO240357 ` allocation 

> Does torch install the cuda version?

I am re-creating a new instance and I will report back.

**Comment by jcfr** [comment]
> re: Pytorch

![image](https://github.com/user-attachments/assets/e3904f3d-d717-4e94-bb05-a86d344ac1ed)


> re: nvidia-driver-550-server-open

Attempting to install the package confirm it is already installed ....

```
$ sudo apt-get install nvidia-driver-550-server-open
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nvidia-driver-550-server-open is already the newest version (550.127.08-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by jcfr** [comment]
After inspecting the code associated with the function `PyTorchUtils.nvidiaDriverVersionInformation()`[^1], it is calling `light_the_torch._cb._detect_nvidia_driver_version()` which itself calls `nvidia-smi`. Running the corresponding command directly on the instance allows to gain additional insight:

```
$ nvidia-smi --query-gpu=driver_version
Failed to initialize NVML: Driver/library version mismatch
NVML library version: 550.127
```

[^1]: https://github.com/fepegar/SlicerPyTorch/blob/e1c85cc0a62e92fa6c38223cd88c611906adb60e/PyTorchUtils/PyTorchUtils.py#L115-L129

[^2]: https://github.com/pmeier/light-the-torch/blob/33397cbe45d07b51ad8ee76b004571a4c236e37f/light_the_torch/_cb.py#L133-L148

**Comment by jcfr** [comment]
Following this suggestion[^1], I ended up restarting the system. Re-running the command now completes:

```
$ nvidia-smi --query-gpu=driver_version --format=csv
driver_version
550.127.08
```

That said, `PyTorchUtils` reports "cpu":

![image](https://github.com/user-attachments/assets/d3968a08-4363-459d-8c3e-bb012115de9e)


To address the reboot aspect, we could look into using the `reboot` module provided by ansible[^2]. This is consistent with the approach that has been implemented in `NVIDIA/ansible-role-nvidia-driver`[^3]

[^1]: https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch/43023000#43023000

[^2]: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html

[^3]: https://github.com/NVIDIA/ansible-role-nvidia-driver/blob/8946eefeb5442761edef6853665074e1306391a0/tasks/main.yml#L50-L52

**Comment by jcfr** [comment]
Within "PyTorchUtils", after uninstalling torch, restarting Slicer, re-running the torch installation and restarting, we can see that the GPU version is now installed:

![image](https://github.com/user-attachments/assets/9224b91f-6e86-4bf4-baa3-93d1834c9990)

**Comment by jcfr** [comment]
Since attempting to use the ansible `reboot` module is not possible because the associated playbook is executed from the instance intended to be rebooted, a different approach is being evaluated.

Instead, the reboot is being performed from the "create-instance" workflow.

**Comment by muratmaga** [comment]
I have started a brand new instance on the Test site. Pytorch was not isntalled. I have installed as part of memos, and everything worked fine. So it looks good to me.

It is important not to run the SLicer via the launcher (or rather vglrun command), since that breaks the torch is a separate issue. But I think you can merge these now.

**Comment by jcfr** [comment]
Fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/e9d099b0c
2. **`MorphoCloudWorkflow`** via commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/52601622bd5be1a2bc4e6f1309dfa9287193ad9d
3. **`MorphoCloudInstances`** via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/be836b29d5b01c17b071e3bf7a13e52619603df3
