### ISSUE TITLE
Github action outputs too verbose

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#68]
Now that we have a good understanding of the github actions, I think we can trim down the amount of comments they are generating. Particularly the ones about the instance name, volume, email format checks are not very useful to the user and add many lines to comment section. More importantly, I thinkusers  simply ignore the issues page comments when there are that many comments (that is important stuff gets lost in the noise).

We have some instance that have almost 1000 comments in them, making it difficult to get to the bottom of the issue page to shelve and unshelve the instance. 

I think the output that are important:

* List of action commands
* Any error, formating problem, and unexpected input should generate a comment for user to take action.
* Progress bar (with the check marks).

**Comment by jcfr** [comment]
The following improvements have been implemented and deployed

## Simplify status report if all tests pass

Implemented via commit 5f1d3ee and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/19c6603d-48c7-44af-867a-ae58abc06aa7) | ![image](https://github.com/user-attachments/assets/85686736-ad4a-4bfe-857a-d0d276ca83d7) |

## Append instance and volume names to issue description

Implemented via commit fde4493 and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

| Before | After |
|--|--|
| | |
| ![image](https://github.com/user-attachments/assets/017cf200-5ca9-4bd3-8383-006b366ad63f) | ![image](https://github.com/user-attachments/assets/ccc4f4e8-c629-47b7-8e80-93f0a2bec159) |

## Remove redundant comment posted by triggering workflow

Implemented via commit 334df2e and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/e3124e3e-98a5-4a0e-aa4c-7ec8bd91916d) | 
![image](https://github.com/user-attachments/assets/365aabd4-d533-4e4a-b6f2-986c473bf9e7) |


## Re-organize validation status to take less vertical space

Implemented via commite c55302 and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/bbabca13-1ba8-4b25-a7fc-d79393ee6d4f) | ![image](https://github.com/user-attachments/assets/e9b07d51-9922-49cb-8c64-bca90d9e1245) |


## Improve readability of control instance success message

Implemented via commit d85cdd6 and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/a4cc5133-61ad-4043-b2ae-8af940b2f19d) | ![image](https://github.com/user-attachments/assets/d366a65b-d684-42fb-bfc9-6e4e68d565b9) |


## Simplify action log links in informational messages

Implemented via commit 352806e and deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/5d00a03a5e15d789659575abc6a6e53ea51f7e32

**Comment by jcfr** [comment]
The following improvements have been implemented and were all deployed via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/8343b3dd4202055fd2ffd63c4fcd108d40c89b10

## Shorten messages associated with successful command execution

| Commit | Before | After |
|--|--|--|
| https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/1799dad58612affe6cc7a3a073dd7a45b484cceb | ![image](https://github.com/user-attachments/assets/60ed228b-8dbc-4fbc-acf3-3cf3e423505c) | ![image](https://github.com/user-attachments/assets/d5d699aa-30dd-4299-9635-691c3acd6356) |
