### ISSUE TITLE
need approved label for /create command

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#7]
Without a visual label like **approved** I cannot tell which of the issues I actually approved and they are going through the motions, versus ones I need to actually review and issue /create command, until the instance created label is affixed.

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/7593cb98ff05fdf49f25c2942da8cd11faabd699
