### ISSUE TITLE
Update Slicer from 5.7.0 r33134 to r33153

### ISSUE THREAD

**Issue by jcfr** [MorphoCloud/MorphoCloudWorkflow#74]
from @muratmaga 

> I have tested todays build on Mac, and that has the fix we need. So between now and Sunday, you will need to the update the image to use revision 33153

**Comment by jcfr** [comment]
Since linux build associated with r33153 did not complete, r33155 is used instead.

Changes integrated since r33153 are listed at https://github.com/Slicer/Slicer/compare/b9b93965c381feb90f97faa057ec026d146633c0...1af67ed6f1411d9dac9f8d7fe246469bb0556569

**Comment by muratmaga** [comment]
Later releases are also fine just needs 33153 or higher

**Comment by jcfr** [comment]
Fixes have been implemented and deployed across multiple projects:

1. **`exosphere`** via commit https://github.com/MorphoCloud/exosphere/commit/4546a412a
2. **`MorphoCloudWorkflow`** via commit https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/a644d5358424037f21581f7b846c27a9f30c560f
3. **`MorphoCloudInstances`** via commit https://github.com/MorphoCloud/MorphoCloudInstances/commit/ae0c4dda18d063e59eabc2e834ff0c62a4479fc0

--- 

Updated Slicer is installed:

![image](https://github.com/user-attachments/assets/db225292-f05c-4225-9952-e31828116099)
