### ISSUE TITLE
Need to change the text for /email from admin to admin and user

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#8]
Users can indeed request emails, but the default text in the issues page says /email is an Admin command. Should be revised to admin, user

**Comment by jcfr** [comment]
The `/email` command is currently reserved for administrator, we will update it so that it can be specified by both the "Issue Creator" and "Admin"

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/3a6b7b67184392b8c5c12e7d1f3c55773b5d74b0
