### ISSUE TITLE
pip install missing packages

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#9]
SlicerMorph requires some packages to be install at the first time when you switch to a module. Examples of these modules are:

GPA: Pandas
ALPACA: ITK
MorphoSourceImport: pyMorphosource

These are required to be installed again, every time an instance is built from scratch. Would it be possible to preload them somehow?

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/exosphere/compare/4327df761f56c00b2e9b580c38dd517267a0b5f9...a2e2381f31647694e80e2baf3e5d0ec7b5c42ffb deployed through https://github.com/MorphoCloud/MorphoCloudInstances/commit/1a6e47de37e2803dca9f2a031d1eb238a35b281a
